### ISSUE TITLE
Missing header guards

### ISSUE THREAD

**Issue by BrentWilkins** [sparkfun/HTU21D_Breakout#3]

**Comment by nseidle** [comment]
Hey Brent - can you tell me more? What are header guards?

**Comment by BrentWilkins** [comment]
Quickly, they prevent a header from being included more than once causing symbol redefinitions.  You can find more info here: https://en.wikipedia.org/wiki/Include_guard It appears that many of your headers are missing them.  I first noticed it due to this pull request to fix another one: https://github.com/sparkfun/SparkFun_MPL3115A2_Breakout_Arduino_Library/pull/1

**Comment by nseidle** [comment]
Got it. Should be fixed in next push.
