### ISSUE TITLE
Negative RH Readout?

### ISSUE THREAD

**Issue by epillar** [sparkfun/HTU21D_Breakout#4]
So I want to thank you first off for making this code readily available. It's helped me a lot with getting my project up and running.

 The temperature seems to be fine, but when I approach ~ 60% RH the sensor starts to read like -67% RH. As the RH increases further, it reads less negative. So from 60 to near 70% RH it outputs -67 to -58%

Is there something wrong with the sensor or is there a way I can code around this.

**Comment by nseidle** [comment]
Hi epillar,

I apologize for the very slow reply! I was not able to replicate your issue. We just updated the library with a handful of new features. Please post if you are still having issues.
