### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [sparkfun/HTU21D_Breakout#5]
In SparkFun_HTU21D_Example.ino, there is a while-loop with a delay after the Wire.requestFrom() call. That while-loop is not needed and that delay is not needed.

When the Wire.requestFrom() function returns, the I2C transaction has completely finished and the received data is in the receive buffer in the Wire library. The Wire.read() only reads data from that buffer.

To test if a I2C error or I2C collision did happen, only one test is needed for the number of received bytes. That can be the return value of Wire.requestFrom() or with Wire.available().

**Comment by nseidle** [comment]
You are correct, a Wire.requestFrom() will return a value without blocking the rest of the code. However, if the sensor is internally calculating, requestFrom will return zeros. These while-loop with delay tricks may be necessary for some sensors while we wait for the sensor to complete its calcs. (I haven't yet dug into the MPL3115A2 to figure out if it is or is not one).

    //Hang out while measurement is taken. datasheet says 50ms, practice may call for more
    byte toRead;
    byte counter;
    for (counter = 0, toRead = 0 ; counter < MAX_COUNTER && toRead != 3 ; counter++)
    {
      delay(DELAY_INTERVAL);

      //Comes back in three bytes, data(MSB) / data(LSB) / Checksum
      toRead = _i2cPort->requestFrom(HTU21D_ADDRESS, 3);
    }

The current implementation works well. Please create a pull request if there's a more elegant solution.

**Comment by nseidle** [comment]
This repo just has a sub-branch of the library. Please see https://github.com/sparkfun/SparkFun_HTU21D_Breakout_Arduino_Library for actual library work.

**Comment by Koepel** [comment]
Sorry, I was confused with the repo's. 
The new code is okay. I think the delay can be 1ms as well. That might generate about 20 trials on the I2C bus, but that's no problem.

**Comment by nseidle** [comment]
Awesome! Thanks for trying to make things better - we welcome the help.
